### ISSUE TITLE
SECURITY: CSRF in multible views

### ISSUE THREAD

**Issue by Akasch** [opatut/dudel#105]
The following views don't do any csrf checking, and are mostly via GET. Most of them should be done via POST.

- [x] group_disband
- [x] group_make_admin
- [x] group_leave
- [x] poll_delete_comment
- [x] poll_invitation_delete
- [x] poll_invitation_resend
- [x] poll_invitations_resend_all
- [x] poll_edit_choices (case: ChoiseForm, subcase toggle)
- [x] poll_edit_value (case "toggle")
- [x]  poll_delete
- [x] poll_vote_delete

The problem is if I fix it on hotfix i will get a big merge conflict on master

**Comment by opatut** [comment]
Please verify that the problem is fixed with 301cf86.

**Comment by Akasch** [comment]
I would set default consume=True and only disable it where it has to consumed more when once. As a minimum it should be enable at the decorator, as there it is not possible to need to consume twice as far as I can see.
