### ISSUE TITLE
Polls do not expire

### ISSUE THREAD

**Issue by RalfJung** [opatut/dudel#108]
Steps to reproduce:

* Create a poll with expiry, e.g. "tomorrow"
* Wait a while (say, a week)
* Execute the cronjob manually (`./manage.py cron`)
* Go to the poll website

Actual behavior:
The poll is shown

Expected behavior:
The poll is not shown.

I am using the `hotfix` branch.

**Comment by opatut** [comment]
Expiry does not equal autodeletion date.

Expired polls should only not be editable anymore (especially one cannot cast more votes or edit existing ones).

Auto-deletion takes place a fixed date after the last modification (currently hard-coded to 60 days in `Poll.should_auto_delete`). 

The `last_changed` date is being calculated using the expiry date, all vote dates, and all comment dates.

Please check that the behaviour is as described. You can test by setting the expiry date >2 months in the past, or changing your system clock to the future.

**Comment by RalfJung** [comment]
> Expiry does not equal autodeletion date.
> 
> Expired polls should only not be editable anymore (especially one cannot cast more votes or edit existing ones).

Oh, I see. This was not clear to me. I guess everything works as
expected then. It would be rgeat if some tooltip or note below the
"expiry date" line or something would explain what the behaviour of
expiration is.

> Please check that the behaviour is as described. You can test by setting the expiry date >2 months in the past, or changing your system clock to the future.

I won't change the system clock of my server ;-) .
I created a poll with expiry date Jan 1st of this year, and it is still
accessible after running the cronjob. However, the last modification was
just recently (creation), so I don't see how this would trigger
auto-deletion.

**Comment by Akasch** [comment]
On our Server the auto delete works as expected.

**Comment by RalfJung** [comment]
I can report back on this in 50 days. ;-)
