### ISSUE TITLE
"Coordinated time" alert while user creates poll

### ISSUE THREAD

**Issue by picobyte** [opatut/dudel#49]
When creating a new poll, the first thing presented to the user when they enter the date/time selection wizard is the alert informing them that the dates and times will be localized without an obvious way to change that before selecting a date:

![dudel](https://cloud.githubusercontent.com/assets/4601206/5750697/adce3b40-9c58-11e4-9654-c347e8674051.png)

I suggest to either
a) remove the tooltip and making new polls non-localized by default (probably the least confusing option for some users)
or
b) add a way to immediately change this setting so as to not leave users wondering what to do if they do not want this while creating the poll.

**Comment by opatut** [comment]
Polls should be non-localized by default, this was indeed a bug, not setting the timezone when the creator was not logged in. Fixed soon :)
