### ISSUE TITLE
Invitation for a specific string causes internal server error

### ISSUE THREAD

**Issue by frmwrk123** [opatut/dudel#61]
When I tried to invite 08letsch to a poll, it always ended in an internal server error. Any other string - even nonsense - was handled useful (in the case of nonsense by showing an error alert).

**Comment by Akasch** [comment]
We will look into it tomorrow. I think i know that happens here

**Comment by Akasch** [comment]
It is fixed now

**Comment by Akasch** [comment]
can be closed, the source of the error was some missing config values
