### ISSUE TITLE
Not all dependencies are documented: sass missing

### ISSUE THREAD

**Issue by RalfJung** [opatut/dudel#75]
Even after installing all the dependencies, I the following error appeared in my apache logfile:
```
OSError: [Errno 2] No such file or directory
```
The problem was that I did not have the Debian package `ruby-sass` installed. After installing it, this error disappeared - but I don't know whether any other dependencies are missing.

**Comment by opatut** [comment]
Fixed in ed00d3205d7b4bc546abe7ceed71a6a39e68bacd.
