### ISSUE TITLE
Provide "list of all Dudels" for admins

### ISSUE THREAD

**Issue by RalfJung** [opatut/dudel#83]
Subject pretty much says it all :)

**Comment by picobyte** [comment]
Well, we already have https://dudel.example.org/admin. Probably we didn't document that anywhere.

**Comment by RalfJung** [comment]
Indeed, you did not, or I missed it. Simply adding a link to that in the
menu of admin users would be great!

**Comment by opatut** [comment]
> Simply adding a link to that in the
menu of admin users would be great!

See #73
