### ISSUE TITLE
Message on each startup: "Raven is not configured"

### ISSUE THREAD

**Issue by RalfJung** [opatut/dudel#85]
Each time dudel is started or imported, the following error is printed:
```
Raven is not configured (logging is disabled). Please see the documentation for more information.
```
This happens even when running the scripts in `scripts/`, or when running custom scripts that import stuff from `dudel`. In particular, when automatically creating polls in a cronjob, this means that the cronjob will generate an email.

**Comment by Akasch** [comment]
Raven is the Client for Sentry. We use it for error reporting. I have made a config option to disable it in #87

**Comment by RalfJung** [comment]
Great! For now, I just commented out these lines, which works. I'll update when your pull request gets merged (and after figuring out whether running dudel from master in a production environment is a good idea...).

**Comment by Akasch** [comment]
running from master was sometimes not a good idea because of missing migrations. But there are some Security patches since V 2.0.0, so if you deploy it you want to take them too. I think at the moment the master should work, but i can't guarantee it.
