### ISSUE TITLE
How to delete expired polls automatically (cronjob)

### ISSUE THREAD

**Issue by RalfJung** [opatut/dudel#93]
Expired polls are not deleted on my server. I assume that's because I did not do any setup for the cron job. There should be documentation on what to do.

I am using version 2.0.0 with the "SECURITY" patches cherry-picked.

**Comment by Akasch** [comment]
This is the cronjob discussed a few days ago, for witch i wanted to write some documentation. I will do tomorrow for sure

**Comment by RalfJung** [comment]
Well, I am using the stable version not including your patch, so I am not sure how much that would even help?

**Comment by Akasch** [comment]
you can call /api/cron over http to trigger the cronjob before my patch

**Comment by RalfJung** [comment]
So the idea is/was to setup a cronjob that does `curl .../api/cron`?

**Comment by Akasch** [comment]
yes. In the next version this will be replaced by a shell command
