### ISSUE TITLE
Data loos on modify date of poll

### ISSUE THREAD

**Issue by Akasch** [opatut/dudel#95]
Bug report from a User:

    Moin Server-Ag,

    ich hab grad ein Dudle laufen, habe dann nachträglich einen weiteren
    Termin hinzugefügt. Das dadurch alle bisher abgegebenen Antworten
    komplett gelöscht werden, ist ein ziemlich unschöner Bug.
    [...]

fix will follow in some minutes

**Comment by opatut** [comment]
Closed with 32ce93ea7bb9042e30e727a41c77e6c391dfea3b. Thank you.
